words:
  - compat
  - grammyjs
  - lowdb
  - nodemon
  - pino
  - reekystive
  - sequentialize
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
  - pnpm-lock.yaml
  - node_modules
